"""cleanup admin row

Revision ID: d7972a53e781
Revises: 
Create Date: 2026-09-30 19:11:27.055829

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd7972a53e781'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('barber', schema=None) as batch_op:
        batch_op.drop_column('phone')

    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.alter_column('customer_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('barber_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('service_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_booking_barber_id'))
        batch_op.drop_index(batch_op.f('ix_booking_customer_id'))
        batch_op.drop_index(batch_op.f('ix_booking_service_id'))
        batch_op.drop_constraint(batch_op.f('fk_booking_customer'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_booking_service'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_booking_barber'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'service', ['service_id'], ['id'])
        batch_op.create_foreign_key(None, 'customer', ['customer_id'], ['id'])
        batch_op.create_foreign_key(None, 'barber', ['barber_id'], ['id'])

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('method', sa.String(length=20), nullable=True))
        batch_op.alter_column('booking_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('amount',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('ix_payment_booking_id'))
        batch_op.drop_constraint(batch_op.f('fk_payment_booking'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'booking', ['booking_id'], ['id'])

    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('role')

    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('payment', schema=None) as batch_op:
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_payment_booking'), 'booking', ['booking_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('ix_payment_booking_id'), ['booking_id'], unique=False)
        batch_op.alter_column('amount',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_nullable=False)
        batch_op.alter_column('booking_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.drop_column('method')

    with op.batch_alter_table('booking', schema=None) as batch_op:
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint(None, type_='foreignkey')
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint(None, type_='foreignkey')
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_booking_barber'), 'barber', ['barber_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_booking_service'), 'service', ['service_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_booking_customer'), 'customer', ['customer_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('ix_booking_service_id'), ['service_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_barber_id'), ['barber_id'], unique=False)
        batch_op.alter_column('service_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('barber_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('customer_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    with op.batch_alter_table('barber', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', mysql.VARCHAR(length=20), nullable=True))

    # ### end Alembic commands ###
